### ISSUE TITLE
Google Colab dependencies 

### ISSUE THREAD

**Issue by OutofAi** [SusungHong/SEG-SDXL#1]
Great work and great paper, considering the colab links may I suggest add this to an initial cell in the notebook to fix the dependency issues on colab? 

```
import sys

if 'google.colab' in sys.modules:
    !pip install diffusers
    !git clone https://github.com/SusungHong/SEG-SDXL
    %cd SEG-SDXL
```

**Comment by SusungHong** [comment]
Thank you for letting me know! I incorporated the changes you suggested.
